dist: trusty
language: cpp
compiler:
 - gcc
 - clang
install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qt5-default qtdeclarative5-dev
script:
 - mkdir build && cd build
 - cmake ..
 - cmake --build . --target all
